version: "3.8"

services:
  node:
    image: node:16
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - .:/home/node/app
    ports:
      - 80:3000
#    command:

  database:
    image: mariadb:10.3
    restart: always
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: prisma

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: database
      PMA_USER: admin
      PMA_PASSWORD: admin
    depends_on:
      - database
    ports:
      - 8080:80
